"""
[AI_DIRECTIVE]
ROL: Primitivas de persistencia KV cache a disco + state container para startup
OBJETIVO: Proveer load/save de safetensors, hashing de prefijo, restauración
          de snapshots congelados. Usado por TPC (tool_prefix_cache) y server.py.
ENTRADAS: KV cache arrays, token lists, paths
SALIDAS: Archivos .safetensors + .hash en disco, snapshots restaurados en memoria
REGLAS INVIOLABLES:
- Prohibido tomar decisiones de evicción — eso lo hace el caller
- Prohibido crashear el servidor en operaciones de disco (best-effort)
- Las funciones son primitivas puras: no acceden a globals del server
SSoT: TPC (tool_prefix_cache.py) es la SSoT para el prefix cache.
      Este módulo provee las primitivas de I/O que TPC consume.
"""

import copy
import hashlib
import logging
import struct
import threading
import time
from pathlib import Path
from typing import Any, List, Optional, Tuple

from supermlx.cache_types import is_recurrent_layer

import mlx.core as mx
from mlx_lm.models.cache import make_prompt_cache

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════════════════════════════════════
# HASHING
# ═══════════════════════════════════════════════════════════════════════════════

def compute_prefix_hash(
    tokens: List[int],
    model_path: Optional[str] = None,
    kv_bits: Optional[int] = None,
) -> str:
    """
    Compute MD5 hash of a token array + model identity + quantization config.

    Deterministic, format-invariant: the same sequence of token IDs with the
    same model and kv_bits always produces the same hash. Including model_path
    and kv_bits prevents loading a cache generated by a different model or
    quantization level (same-family models share tokenizers, so tokens alone
    are not sufficient to distinguish them).
    """
    token_bytes = struct.pack(f"<{len(tokens)}i", *tokens)
    h = hashlib.md5(token_bytes)
    if model_path is not None:
        h.update(model_path.encode("utf-8"))
    if kv_bits is not None:
        h.update(str(kv_bits).encode("utf-8"))
    return h.hexdigest()


# ═══════════════════════════════════════════════════════════════════════════════
# CACHE PERSISTENCE (save/load KV state to/from disk)
# ═══════════════════════════════════════════════════════════════════════════════

CACHE_FORMAT_VERSION = 2

def save_cache(
    tokens: List[int],
    prompt_cache: Any,
    path: Path,
    prefix_hash: Optional[str] = None,
    log_fn=None,
) -> bool:
    """
    Serialize KV cache to disk using MLX safetensors.

    Saves token sequence + per-layer K/V arrays + offsets.
    If prefix_hash is provided, also saves warmup_cache.hash.
    Best-effort: never crashes the server on failure.

    Args:
        tokens: Token IDs corresponding to the cached KV state.
        prompt_cache: List of cache layer objects (KVCache/ArraysCache).
        path: Target file path (.safetensors).
        prefix_hash: Optional MD5 hash to save alongside.
        log_fn: Optional logging callback fn(emoji, message).

    Returns:
        True on success, False on failure.
    """
    _log = log_fn or (lambda *a: None)
    _t0 = time.perf_counter()
    path = Path(path)

    try:
        if not tokens or not prompt_cache:
            _log("⚠️", "save_cache: empty tokens or cache — skipping")
            return False

        path.parent.mkdir(parents=True, exist_ok=True)
        weights = {}

        # Metadata
        import numpy as np
        weights["__tokens__"] = mx.array(tokens, dtype=mx.int32)
        weights["__version__"] = mx.array([CACHE_FORMAT_VERSION], dtype=mx.int32)

        # Serialize each layer
        for i, layer in enumerate(prompt_cache):
            if is_recurrent_layer(layer):
                # Recurrent layer (ArraysCache): save the cache/state arrays
                cache_data = getattr(layer, 'cache', getattr(layer, 'state', []))
                for j, arr in enumerate(cache_data):
                    if arr is not None:
                        weights[f"layer_{i}_recurrent_{j}"] = arr
                # Save offset/position
                offset = getattr(layer, 'offset', None)
                if offset is not None:
                    weights[f"layer_{i}_offset"] = mx.array([int(offset)], dtype=mx.int32)
            else:
                # Standard KVCache layer
                keys = getattr(layer, "keys", None)
                values = getattr(layer, "values", None)
                if keys is not None:
                    weights[f"layer_{i}_keys"] = keys
                if values is not None:
                    weights[f"layer_{i}_values"] = values
                # Store offset
                offset = getattr(layer, "offset", None)
                if offset is not None:
                    weights[f"layer_{i}_offset"] = mx.array([int(offset)], dtype=mx.int32)
                # Store step (for rotary position tracking)
                step = getattr(layer, "step", None)
                if step is not None:
                    weights[f"layer_{i}_step"] = mx.array([int(step)], dtype=mx.int32)

        mx.savez(str(path), **weights)

        _elapsed = time.perf_counter() - _t0
        _size_mb = path.stat().st_size / 1e6 if path.exists() else 0

        _log(
            "💾",
            f"Cache saved: {path.name} | {len(tokens)} tokens | "
            f"{_size_mb:.1f}MB | {_elapsed:.2f}s",
        )

        # Save hash alongside
        if prefix_hash:
            hash_path = path.parent / "warmup_cache.hash"
            hash_path.write_text(prefix_hash)

        return True

    except Exception as e:
        _log("⚠️", f"save_cache FAILED: {type(e).__name__}: {e}")
        return False


def load_cache(
    path: Path,
    model: Any,
    max_kv_size: int,
    is_vlm: bool = False,
    log_fn=None,
) -> Tuple[Optional[List[int]], Optional[Any]]:
    """
    Deserialize KV cache from disk.

    Creates a fresh prompt_cache from the model and populates it with the
    saved K/V arrays. Validates format version and array shapes.

    Args:
        path: Path to the .safetensors file.
        model: The loaded MLX model (needed for make_prompt_cache).
        max_kv_size: Maximum KV cache size in tokens.
        is_vlm: Whether the model is a vision-language model.
        log_fn: Optional logging callback fn(emoji, message).

    Returns:
        (tokens, prompt_cache) on success, (None, None) on failure.
    """
    _log = log_fn or (lambda *a: None)
    path = Path(path)

    if not path.exists():
        _log("ℹ️", f"load_cache: {path.name} not found — cold start")
        return None, None

    try:
        _t0 = time.perf_counter()
        weights = dict(mx.load(str(path)))

        # Version check
        version = int(weights.get("__version__", mx.array([1]))[0].item())
        if version > CACHE_FORMAT_VERSION:
            _log("⚠️", f"load_cache: unsupported version {version} — skipping")
            return None, None

        # Extract tokens
        tokens_arr = weights.get("__tokens__")
        if tokens_arr is None:
            _log("⚠️", "load_cache: no __tokens__ in saved cache — skipping")
            return None, None
        tokens = tokens_arr.tolist()

        # Create fresh cache from model
        prompt_cache = make_prompt_cache(model, max_kv_size)

        # Populate layers
        for i, layer in enumerate(prompt_cache):
            if is_recurrent_layer(layer):
                # Recurrent layer: restore cache/state arrays
                cache_data = getattr(layer, 'cache', getattr(layer, 'state', []))
                for j in range(len(cache_data)):
                    key = f"layer_{i}_recurrent_{j}"
                    if key in weights:
                        cache_data[j] = weights[key]
                # Restore offset
                offset_key = f"layer_{i}_offset"
                if offset_key in weights:
                    offset_val = int(weights[offset_key][0].item())
                    if hasattr(layer, 'offset'):
                        layer.offset = offset_val
            else:
                # Standard KVCache layer
                keys_key = f"layer_{i}_keys"
                values_key = f"layer_{i}_values"
                if keys_key in weights and values_key in weights:
                    layer.keys = weights[keys_key]
                    layer.values = weights[values_key]
                # Restore offset
                offset_key = f"layer_{i}_offset"
                if offset_key in weights:
                    offset_val = int(weights[offset_key][0].item())
                    if hasattr(layer, 'offset'):
                        layer.offset = offset_val
                # Restore step
                step_key = f"layer_{i}_step"
                if step_key in weights:
                    step_val = int(weights[step_key][0].item())
                    if hasattr(layer, 'step'):
                        layer.step = step_val

        _elapsed = time.perf_counter() - _t0
        _log(
            "🔥",
            f"Cache loaded: {path.name} | {len(tokens)} tokens | "
            f"{len(prompt_cache)} layers | {_elapsed:.2f}s",
        )
        return tokens, prompt_cache

    except Exception as e:
        _log(
            "⚠️",
            f"DPC: disk load FAILED ({type(e).__name__}: {e}) — will cold-start",
        )
        return None, None


# ═══════════════════════════════════════════════════════════════════════════════
# FROZEN CACHE RESTORE (pollution recovery for FIX-31)
# ═══════════════════════════════════════════════════════════════════════════════

def restore_frozen_snapshot(
    frozen_cache: Any,
    log_fn=None,
) -> Optional[Any]:
    """
    Restore a clean prompt cache from a frozen snapshot.

    Creates new copies of all layer objects so the frozen snapshot remains
    immutable for future restores.

    Args:
        frozen_cache: Previously frozen cache.
        log_fn: Optional logging callback fn(emoji, message).

    Returns:
        A fresh deep copy of the frozen cache, or None on failure.
    """
    _log = log_fn or (lambda *a: None)
    if frozen_cache is None:
        return None
    try:
        restored = []
        for layer in frozen_cache:
            if is_recurrent_layer(layer):
                new_layer = copy.copy(layer)
                if hasattr(layer, 'cache'):
                    new_layer.cache = [
                        mx.array(c) if c is not None else None
                        for c in layer.cache
                    ]
                elif hasattr(layer, 'state'):
                    new_layer.state = [
                        mx.array(c) if c is not None else None
                        for c in layer.state
                    ]
                restored.append(new_layer)
            else:
                restored.append(copy.deepcopy(layer))
        _log("🧊", f"Frozen cache restored | {len(restored)} layers")
        return restored
    except Exception as e:
        _log("⚠️", f"Frozen restore failed ({e})")
        return None


# ═══════════════════════════════════════════════════════════════════════════════
# STATE CONTAINER (shared between startup thread and request handler)
# ═══════════════════════════════════════════════════════════════════════════════

class DPCState:
    """
    Shared state for the cache lifecycle.

    Thread-safe via the warmup_done event and explicit locking where needed.
    Created once at boot, referenced by the request handler.
    """
    def __init__(self) -> None:
        self.prefix_hash: Optional[str] = None       # MD5 from disk (loaded at boot)
        self.frozen_cache: Optional[Any] = None       # Immutable snapshot for pollution recovery
        self.frozen_tokens: Optional[List[int]] = None  # Tokens for the frozen cache
        self.disk_cache_saved: bool = False            # True after first MAIN save to disk
        self.embedded_cache_saved: bool = False        # True after first EMBEDDED save to disk
        self.warmup_done = threading.Event()           # Set when boot sequence completes
        self.first_capture_done: bool = False          # True after auto-capture on first request
