"""
warmup_manager.py — Dynamic Prefix Capture (DPC) for SuperMLX
══════════════════════════════════════════════════════════════════════════════

Manages KV cache warmup lifecycle with zero manual seed files.

Architecture inspired by SGLang (RadixAttention) and vLLM (Automatic Prefix
Caching), adapted for MLX's flat ArraysCache/KVCache memory model.

Flow:
  1. Boot:    Load prefix hash from disk (instant, <1ms)
  2. Request: Detect boundary → hash prefix → compare with disk
              Match  → load .safetensors → instant warm cache
              Miss   → cold start → auto-capture → save to disk
  3. Restart: Back to step 1 (self-healing if SOUL/tools changed)

Files managed:
  - logs/warmup_cache.safetensors  — KV state of the static prefix
  - logs/warmup_cache.hash         — MD5 of the prefix token array

Replaces: warmup_seed.txt, .seed_hash, FEATURE_WARMUP_AUTO_UPDATE
"""

import copy
import hashlib
import math
import struct
import threading
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from supermlx.cache_types import is_recurrent_layer

import mlx.core as mx
from mlx_lm.models.cache import (
    make_prompt_cache,
    can_trim_prompt_cache,
    trim_prompt_cache,
)



# ═══════════════════════════════════════════════════════════════════════════════
# HASHING
# ═══════════════════════════════════════════════════════════════════════════════

def compute_prefix_hash(
    tokens: List[int],
    model_path: Optional[str] = None,
    kv_bits: Optional[int] = None,
) -> str:
    """
    Compute MD5 hash of a token array + model identity + quantization config.

    Deterministic, format-invariant: the same sequence of token IDs with the
    same model and kv_bits always produces the same hash. Including model_path
    and kv_bits prevents loading a cache generated by a different model or
    quantization level (same-family models share tokenizers, so tokens alone
    are not sufficient to distinguish them).
    """
    token_bytes = struct.pack(f"<{len(tokens)}i", *tokens)
    h = hashlib.md5(token_bytes)
    if model_path is not None:
        h.update(model_path.encode("utf-8"))
    if kv_bits is not None:
        h.update(str(kv_bits).encode("utf-8"))
    return h.hexdigest()




# ═══════════════════════════════════════════════════════════════════════════════
# CACHE PERSISTENCE (save/load KV state to/from disk)
# ═══════════════════════════════════════════════════════════════════════════════

CACHE_FORMAT_VERSION = 2

def save_cache(
    tokens: List[int],
    prompt_cache: Any,
    path: Path,
    prefix_hash: Optional[str] = None,
    log_fn=None,
) -> bool:
    """
    Serialize KV cache to disk using MLX safetensors.

    Saves token sequence + per-layer K/V arrays + offsets.
    If prefix_hash is provided, also saves warmup_cache.hash.
    Best-effort: never crashes the server on failure.

    Args:
        tokens: Token IDs corresponding to the cached KV state.
        prompt_cache: List of cache layer objects (KVCache/ArraysCache).
        path: Destination path for the .safetensors file.
        prefix_hash: MD5 hash of the prefix tokens (saved alongside).
        log_fn: Optional logging callback fn(emoji, message).
    """
    _log = log_fn or (lambda *a: None)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        arrays: Dict[str, Any] = {}
        arrays["tokens"] = mx.array(tokens, dtype=mx.int32)
        arrays["cache_format_version"] = mx.array(
            [CACHE_FORMAT_VERSION], dtype=mx.int32
        )
        # n_kv_layers: count of layers that actually have KV cache state
        # (hybrid models like DeltaNet/Attention have fewer KV layers than total layers)
        saved_layers = 0
        saved_recurrent = 0
        for i, layer in enumerate(prompt_cache):
            # # DEBUG: trace each layer to find why KVCache layers are not saved
            # _has_state = hasattr(layer, "state")
            # _has_keys = hasattr(layer, "keys")
            # _keys_none = layer.keys is None if _has_keys else "N/A"
            # _offset = getattr(layer, "offset", "N/A")
            # _cls = type(layer).__name__
            # if i < 5 or (i % 10 == 0):
            #     _log("DEBUG", f"save layer[{i}] cls={_cls} has_state={_has_state} has_keys={_has_keys} keys_none={_keys_none} offset={_offset}")
            # --- ArraysCache (GatedDeltaNet recurrent state) ---
            # Hybrid models (Qwen3.5/Agents-A1) have GatedDeltaNet layers that use
            # ArraysCache with [conv_state, recurrent_state] instead of KVCache.
            # Persisting this avoids re-computing 30 layers of recurrent state on prefill.
            if hasattr(layer, "state") and isinstance(layer.state, (list, tuple)) and not hasattr(layer, "keys"):
                has_data = any(
                    s is not None and hasattr(s, "shape")
                    for s in layer.state
                )
                if has_data:
                    for part_idx, part in enumerate(layer.state):
                        if part is not None and hasattr(part, "shape"):
                            arrays[f"rs{i}_{part_idx}"] = part
                    arrays[f"rs{i}_n"] = mx.array(
                        [len(layer.state)], dtype=mx.int32
                    )
                    saved_recurrent += 1
                continue
            
            # --- KVCache / QuantizedKVCache ---
            if not hasattr(layer, "keys") or layer.keys is None:
                continue
            offset = int(getattr(layer, "offset", 0))
            if offset == 0:
                continue
            # tree_map converts tuples to lists, so check both types.
            # QuantizedKVCache stores keys/values as 3-element sequences (data, scales, biases).
            is_quantized = isinstance(layer.keys, (tuple, list)) and len(layer.keys) == 3
            if is_quantized:
                # QuantizedKVCache: keys/values are tuples of (data, scales, biases)
                group_size = getattr(layer, "group_size", 64)
                bits = getattr(layer, "bits", 8)
                arrays[f"qmeta{i}"] = mx.array([group_size, bits], dtype=mx.int32)
                for part_idx, part in enumerate(layer.keys):
                    arrays[f"k{i}_{part_idx}"] = part[..., :offset, :]
                for part_idx, part in enumerate(layer.values):
                    arrays[f"v{i}_{part_idx}"] = part[..., :offset, :]
            else:
                # KVCache: keys/values are plain arrays (or single-element lists)
                k_arr = layer.keys[0] if isinstance(layer.keys, list) else layer.keys
                v_arr = layer.values[0] if isinstance(layer.values, list) else layer.values
                arrays[f"k{i}"] = k_arr[..., :offset, :]
                arrays[f"v{i}"] = v_arr[..., :offset, :]
            arrays[f"o{i}"] = mx.array([offset], dtype=mx.int32)
            saved_layers += 1
        # Save actual KV layer count (not total model layers)
        arrays["n_layers"] = mx.array([saved_layers], dtype=mx.int32)
        if saved_recurrent > 0:
            arrays["n_recurrent"] = mx.array([saved_recurrent], dtype=mx.int32)
        # Force evaluation before writing to disk
        live = [v for v in arrays.values() if hasattr(v, "shape")]
        if live:
            mx.eval(*live)
        mx.save_safetensors(str(path), arrays)

        # Save prefix hash alongside the cache
        if prefix_hash:
            save_prefix_hash(prefix_hash, path.parent)

        _log(
            "💾",
            f"DPC: cache saved → {path.name} | format=v{CACHE_FORMAT_VERSION} | "
            f"layers={saved_layers} + {saved_recurrent} recurrent | tokens={len(tokens)}",
        )
        return True
    except Exception as e:
        _log("⚠️", f"DPC: cache save FAILED ({type(e).__name__}: {e})")
        return False


def load_cache(
    path: Path,
    model: Any,
    max_kv_size: int,
    is_vlm: bool = False,
    log_fn=None,
) -> Tuple[Optional[List[int]], Optional[Any]]:
    """
    Deserialize KV cache from disk.

    Reconstructs KVCache layer objects with saved K/V arrays and offsets.
    Returns (tokens, prompt_cache) or (None, None) on any failure.

    Args:
        path: Path to the .safetensors file.
        model: The loaded MLX model (needed for make_prompt_cache).
        max_kv_size: Maximum KV cache size setting.
        is_vlm: Whether the model is a Vision-Language Model.
        log_fn: Optional logging callback fn(emoji, message).
    """
    _log = log_fn or (lambda *a: None)
    if not path.exists():
        return None, None
    try:
        arrays = mx.load(str(path))
        version_array = arrays.get("cache_format_version")
        version = (
            int(version_array.tolist()[0])
            if version_array is not None
            else None
        )
        if version != CACHE_FORMAT_VERSION:
            _log(
                "⚠️",
                "DPC: incompatible cache format "
                f"({version if version is not None else 'legacy'} != "
                f"v{CACHE_FORMAT_VERSION}) — ignoring and cold-starting",
            )
            return None, None
        tokens = arrays["tokens"].tolist()
        if not tokens:
            _log("⚠️", "DPC: disk cache has empty token list — ignoring")
            return None, None

        cache_model = (
            model.language_model
            if is_vlm and hasattr(model, "language_model")
            else model
        )
        prompt_cache = make_prompt_cache(cache_model, max_kv_size=max_kv_size)

        restored_layers = 0
        restored_recurrent = 0
        for i, layer in enumerate(prompt_cache):
            # --- ArraysCache (GatedDeltaNet recurrent state) ---
            rs_n_key = f"rs{i}_n"
            if rs_n_key in arrays:
                n_parts = int(arrays[rs_n_key].tolist()[0])
                state_parts = []
                for p_idx in range(n_parts):
                    part_key = f"rs{i}_{p_idx}"
                    if part_key in arrays:
                        state_parts.append(arrays[part_key])
                    else:
                        state_parts.append(None)
                if hasattr(layer, "state") and not hasattr(layer, "keys"):
                    layer.state = state_parts
                    restored_recurrent += 1
                continue
            
            # --- KVCache / QuantizedKVCache ---
            # Detect format: quantized (k{i}_0) vs plain (k{i})
            is_quantized = f"k{i}_0" in arrays
            if not is_quantized and f"k{i}" not in arrays:
                continue
            o_key = f"o{i}"
            if o_key not in arrays:
                continue
            offset = int(arrays[o_key].tolist()[0])
            if offset == 0:
                continue

            step = int(getattr(layer, "step", 256))
            capacity = math.ceil(offset / step) * step

            if is_quantized:
                # QuantizedKVCache format: restore tuples + convert layer type
                qmeta = arrays.get(f"qmeta{i}")
                group_size = int(qmeta.tolist()[0]) if qmeta is not None else 64
                bits = int(qmeta.tolist()[1]) if qmeta is not None else 8

                def _pad_parts(prefix: str) -> tuple:
                    parts = []
                    for p in range(3):
                        arr = arrays[f"{prefix}{i}_{p}"]
                        current_len = arr.shape[2]
                        if capacity > current_len:
                            pad = mx.zeros(
                                (*arr.shape[:2], capacity - current_len, arr.shape[3]),
                                dtype=arr.dtype,
                            )
                            arr = mx.concatenate([arr, pad], axis=2)
                        parts.append(arr)
                    return tuple(parts)

                # Replace the KVCache layer with a QuantizedKVCache
                from mlx_lm.models.cache import QuantizedKVCache
                qlayer = QuantizedKVCache(group_size=group_size, bits=bits)
                qlayer.keys = _pad_parts("k")
                qlayer.values = _pad_parts("v")
                qlayer.offset = offset
                prompt_cache[i] = qlayer
            else:
                # Plain KVCache format
                saved_k = arrays[f"k{i}"]
                saved_v = arrays[f"v{i}"]
                current_len = saved_k.shape[2]
                if capacity > current_len:
                    pad_len = capacity - current_len
                    zeros_k = mx.zeros(
                        (*saved_k.shape[:2], pad_len, saved_k.shape[3]), dtype=saved_k.dtype
                    )
                    zeros_v = mx.zeros(
                        (*saved_v.shape[:2], pad_len, saved_v.shape[3]), dtype=saved_v.dtype
                    )
                    layer.keys = mx.concatenate([saved_k, zeros_k], axis=2)
                    layer.values = mx.concatenate([saved_v, zeros_v], axis=2)
                else:
                    layer.keys = saved_k
                    layer.values = saved_v
                layer.offset = offset
            restored_layers += 1

        # Force GPU evaluation of all reconstructed tensors
        live = [
            l.keys for l in prompt_cache
            if hasattr(l, "keys") and l.keys is not None
        ]
        # Also eval restored recurrent states (GatedDeltaNet ArraysCache)
        for l in prompt_cache:
            if hasattr(l, "state") and isinstance(l.state, (list, tuple)):
                for s in l.state:
                    if s is not None and hasattr(s, "shape"):
                        live.append(s)
        if live:
            mx.eval(*live)

        _log(
            "💾",
            f"DPC: disk cache loaded | layers={restored_layers} + {restored_recurrent} recurrent | tokens={len(tokens)}",
        )
        # Guard: restored layers must match what was originally saved.
        # Hybrid models (DeltaNet/Attention) save fewer layers than total model layers
        # because DeltaNet layers use recurrent state, not KV cache.
        expected_kv_layers = int(arrays["n_layers"].tolist()[0]) if "n_layers" in arrays else total_layers
        if restored_layers < expected_kv_layers:
            _log(
                "⚠️",
                f"DPC: partial cache ({restored_layers}/{expected_kv_layers} kv-layers) — "
                f"discarding to avoid shape mismatch. Will cold-start.",
            )
            return None, None
        return tokens, prompt_cache
    except Exception as e:
        _log(
            "⚠️",
            f"DPC: disk load FAILED ({type(e).__name__}: {e}) — will cold-start",
        )
        return None, None


# ═══════════════════════════════════════════════════════════════════════════════
# FROZEN CACHE (immutable snapshot for pollution recovery)
# ═══════════════════════════════════════════════════════════════════════════════


def restore_frozen_snapshot(
    frozen_cache: Any,
    log_fn=None,
) -> Optional[Any]:
    """
    Restore a clean prompt cache from a frozen snapshot.

    Creates new copies of all layer objects so the frozen snapshot remains
    immutable for future restores.

    Args:
        frozen_cache: Previously frozen cache (from create_frozen_snapshot).
        log_fn: Optional logging callback fn(emoji, message).

    Returns:
        A fresh deep copy of the frozen cache, or None on failure.
    """
    _log = log_fn or (lambda *a: None)
    if frozen_cache is None:
        return None
    try:
        restored = []
        for layer in frozen_cache:
            if is_recurrent_layer(layer):
                new_layer = copy.copy(layer)
                if hasattr(layer, 'cache'):
                    new_layer.cache = [
                        mx.array(c) if c is not None else None
                        for c in layer.cache
                    ]
                elif hasattr(layer, 'state'):
                    new_layer.state = [
                        mx.array(c) if c is not None else None
                        for c in layer.state
                    ]
                restored.append(new_layer)
            else:
                restored.append(copy.deepcopy(layer))
        _log("🧊", f"DPC: frozen cache restored | {len(restored)} layers")
        return restored
    except Exception as e:
        _log("⚠️", f"DPC: frozen restore failed ({e})")
        return None




class DPCState:
    """
    Shared state for the Dynamic Prefix Capture lifecycle.

    Thread-safe via the warmup_done event and explicit locking where needed.
    Created once at boot, referenced by the request handler.
    """
    def __init__(self):
        self.prefix_hash: Optional[str] = None       # MD5 from disk (loaded at boot)
        self.frozen_cache: Optional[Any] = None       # Immutable snapshot for pollution recovery
        self.frozen_tokens: Optional[List[int]] = None  # Tokens for the frozen cache
        self.disk_cache_saved: bool = False            # True after first MAIN save to disk
        self.embedded_cache_saved: bool = False        # True after first EMBEDDED save to disk
        self.warmup_done = threading.Event()           # Set when boot sequence completes
        self.first_capture_done: bool = False          # True after DPC auto-capture on first request


